using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using GwsBusinessSuite.Application.Abstractions;
using GwsBusinessSuite.Application.ContentStudio;
using Microsoft.Extensions.Options;

namespace GwsBusinessSuite.Infrastructure.Services;

public sealed class SanityReader(HttpClient http, IOptions<SanityOptions> options) : ISanityReader
{
    // Query both standard blog posts and articles generated by this app.
    private string DocTypeFilter => $"_type in [\"post\", \"{options.Value.DocumentType}\"]";

    public async Task<IReadOnlyList<SanityArticleSummary>> GetArticlesAsync(CancellationToken ct = default)
    {
        var opts = options.Value;
        var query =
            $"*[{DocTypeFilter}] | order(coalesce(publishedAt, approvedAt) desc) {{" +
            "\"slug\": slug.current, " +
            "\"title\": coalesce(title, topic), " +
            "\"bodyPlainText\": select(_type == \"post\" => pt::text(body), coalesce(seo.metaDescription, excerpt, bodyMarkdown)), " +
            "\"primaryKeyword\": select(_type == \"post\" => categories[0]->title, primaryKeyword), " +
            "\"publishedAt\": coalesce(publishedAt, approvedAt), " +
            "\"hasMainImage\": defined(mainImage), " +
            "\"mainImageRef\": mainImage.asset._ref" +
            "}";

        var rows = await RunQueryAsync<SanityRawArticle>(query, ct);
        var dataset = DatasetOrDefault(opts);

        return rows
            .Where(a => !string.IsNullOrWhiteSpace(a.Slug))
            .Select(a =>
            {
                var imageUrl = BuildImageUrl(a.MainImageRef, opts.ProjectId, dataset);
                return new SanityArticleSummary(
                    Slug: a.Slug!,
                    Title: a.Title ?? a.Slug!,
                    MetaDescription: Truncate(a.BodyPlainText, 200),
                    PrimaryKeyword: a.PrimaryKeyword,
                    EstimatedReadingTime: EstimateReadingTime(a.BodyPlainText),
                    PublishedAt: a.PublishedAt,
                    HasHeroImage: a.HasMainImage && imageUrl is not null,
                    HeroImageUrl: imageUrl);
            })
            .ToList();
    }

    public async Task<SanityArticleDetail?> GetArticleBySlugAsync(string slug, CancellationToken ct = default)
    {
        var opts = options.Value;
        var safeSlug = slug.Replace("\"", "").Replace("\\", "");
        var query =
            $"*[{DocTypeFilter} && slug.current == \"{safeSlug}\"] {{" +
            "\"slug\": slug.current, " +
            "\"title\": coalesce(title, topic), " +
            "topic, " +
            "\"bodyPlainText\": select(_type == \"post\" => pt::text(body), coalesce(seo.metaDescription, excerpt, bodyMarkdown)), " +
            "body, " +
            "bodyMarkdown, " +
            "\"primaryKeyword\": select(_type == \"post\" => categories[0]->title, primaryKeyword), " +
            "secondaryKeywords, " +
            "\"publishedAt\": coalesce(publishedAt, approvedAt), " +
            "\"authorName\": select(_type == \"post\" => author->name, null), " +
            "\"hasMainImage\": defined(mainImage), " +
            "\"mainImageRef\": mainImage.asset._ref, " +
            "_type" +
            "}";

        var rows = await RunQueryAsync<SanityRawArticle>(query, ct);
        var a = rows.FirstOrDefault();
        if (a is null || string.IsNullOrWhiteSpace(a.Slug))
            return null;

        var dataset = DatasetOrDefault(opts);
        var imageUrl = BuildImageUrl(a.MainImageRef, opts.ProjectId, dataset);

        var markdown = a.Type == "post"
            ? PortableTextToMarkdown(a.Body)
            : a.BodyMarkdown ?? string.Empty;

        var plainText = a.BodyPlainText ?? Truncate(markdown, 500) ?? string.Empty;

        return new SanityArticleDetail(
            Slug: a.Slug,
            Title: a.Title ?? a.Slug,
            Topic: a.Topic,
            MetaDescription: Truncate(a.BodyPlainText, 200),
            ArticleMarkdown: markdown,
            PrimaryKeyword: a.PrimaryKeyword,
            SecondaryKeywords: a.SecondaryKeywords,
            PublishedAt: a.PublishedAt,
            Author: string.IsNullOrWhiteSpace(a.AuthorName) ? "Grant Watson" : a.AuthorName,
            EstimatedReadingTime: EstimateReadingTime(plainText),
            HasHeroImage: a.HasMainImage && imageUrl is not null,
            HeroImageUrl: imageUrl,
            HeroImageAltText: null,
            HeroImageCaption: null);
    }

    // ── Sanity GROQ HTTP helper ────────────────────────────────────────────

    private async Task<List<T>> RunQueryAsync<T>(string query, CancellationToken ct)
    {
        var opts = options.Value;
        if (string.IsNullOrWhiteSpace(opts.ProjectId)) return [];

        var apiVersion = string.IsNullOrWhiteSpace(opts.ApiVersion) ? "2021-10-21" : opts.ApiVersion;
        var dataset = DatasetOrDefault(opts);
        var url = $"https://{opts.ProjectId}.apicdn.sanity.io/v{apiVersion}/data/query/{dataset}?query={Uri.EscapeDataString(query)}";

        if (!string.IsNullOrWhiteSpace(opts.Token))
            http.DefaultRequestHeaders.Authorization = new("Bearer", opts.Token);

        try
        {
            var response = await http.GetAsync(url, ct);
            if (!response.IsSuccessStatusCode) return [];
            var result = await response.Content.ReadFromJsonAsync<SanityQueryResponse<T>>(ct);
            return result?.Result ?? [];
        }
        catch
        {
            return [];
        }
    }

    // ── Portable Text → Markdown ───────────────────────────────────────────

    private static string PortableTextToMarkdown(JsonElement? body)
    {
        if (body is null || body.Value.ValueKind != JsonValueKind.Array)
            return string.Empty;

        var sb = new StringBuilder();

        foreach (var block in body.Value.EnumerateArray())
        {
            if (!block.TryGetProperty("_type", out var typeEl)) continue;

            if (typeEl.GetString() == "block")
            {
                var style = block.TryGetProperty("style", out var styleEl)
                    ? styleEl.GetString() ?? "normal" : "normal";

                var markDefs = block.TryGetProperty("markDefs", out var mdEl) ? mdEl : (JsonElement?)null;
                var lineText = new StringBuilder();

                if (block.TryGetProperty("children", out var children))
                {
                    foreach (var span in children.EnumerateArray())
                    {
                        if (!span.TryGetProperty("_type", out var spanType) ||
                            spanType.GetString() != "span") continue;

                        var text = span.TryGetProperty("text", out var textEl)
                            ? textEl.GetString() ?? string.Empty : string.Empty;

                        var marks = span.TryGetProperty("marks", out var marksEl)
                            ? marksEl.EnumerateArray().Select(m => m.GetString() ?? "").ToList()
                            : [];

                        var isStrong = marks.Contains("strong");
                        var isEm = marks.Contains("em");
                        var isCode = marks.Contains("code");
                        string? linkHref = null;

                        if (markDefs.HasValue)
                        {
                            foreach (var markKey in marks)
                            {
                                foreach (var md in markDefs.Value.EnumerateArray())
                                {
                                    if (md.TryGetProperty("_key", out var k) && k.GetString() == markKey &&
                                        md.TryGetProperty("_type", out var mt) && mt.GetString() == "link" &&
                                        md.TryGetProperty("href", out var href))
                                    {
                                        linkHref = href.GetString();
                                        break;
                                    }
                                }
                                if (linkHref is not null) break;
                            }
                        }

                        if (isCode)   text = $"`{text}`";
                        if (isStrong) text = $"**{text}**";
                        if (isEm)     text = $"*{text}*";
                        if (linkHref is not null) text = $"[{text}]({linkHref})";

                        lineText.Append(text);
                    }
                }

                var line = lineText.ToString();
                var formatted = style switch
                {
                    "h1" => $"# {line}",
                    "h2" => $"## {line}",
                    "h3" => $"### {line}",
                    "h4" => $"#### {line}",
                    "h5" => $"##### {line}",
                    "h6" => $"###### {line}",
                    "blockquote" => $"> {line}",
                    _ => line
                };

                sb.AppendLine(formatted);
                sb.AppendLine();
            }
        }

        return sb.ToString().Trim();
    }

    // ── Helpers ────────────────────────────────────────────────────────────

    private static string? BuildImageUrl(string? imageRef, string projectId, string dataset)
    {
        if (string.IsNullOrWhiteSpace(imageRef) || string.IsNullOrWhiteSpace(projectId))
            return null;

        // "image-{hash}-{w}x{h}-{ext}" → "{hash}-{w}x{h}.{ext}"
        var bare = imageRef.StartsWith("image-") ? imageRef[6..] : imageRef;
        var lastDash = bare.LastIndexOf('-');
        if (lastDash < 0) return null;

        var filename = bare[..lastDash] + "." + bare[(lastDash + 1)..];
        return $"https://cdn.sanity.io/images/{projectId}/{dataset}/{filename}";
    }

    private static string EstimateReadingTime(string? text)
    {
        if (string.IsNullOrWhiteSpace(text)) return "1 min read";
        var words = text.Split([' ', '\n', '\r', '\t'], StringSplitOptions.RemoveEmptyEntries).Length;
        var minutes = Math.Max(1, (int)Math.Ceiling(words / 200.0));
        return $"{minutes} min read";
    }

    private static string? Truncate(string? text, int max)
    {
        if (string.IsNullOrWhiteSpace(text)) return null;
        return text.Length <= max ? text : text[..max].TrimEnd() + "…";
    }

    private static string DatasetOrDefault(SanityOptions opts) =>
        string.IsNullOrWhiteSpace(opts.Dataset) ? "production" : opts.Dataset;
}

internal sealed class SanityQueryResponse<T>
{
    [JsonPropertyName("result")]
    public List<T>? Result { get; init; }
}

internal sealed class SanityRawArticle
{
    [JsonPropertyName("slug")]
    public string? Slug { get; init; }

    [JsonPropertyName("title")]
    public string? Title { get; init; }

    [JsonPropertyName("topic")]
    public string? Topic { get; init; }

    [JsonPropertyName("bodyPlainText")]
    public string? BodyPlainText { get; init; }

    [JsonPropertyName("body")]
    public JsonElement? Body { get; init; }

    [JsonPropertyName("bodyMarkdown")]
    public string? BodyMarkdown { get; init; }

    [JsonPropertyName("primaryKeyword")]
    public string? PrimaryKeyword { get; init; }

    [JsonPropertyName("secondaryKeywords")]
    public string? SecondaryKeywords { get; init; }

    [JsonPropertyName("publishedAt")]
    public DateTimeOffset? PublishedAt { get; init; }

    [JsonPropertyName("authorName")]
    public string? AuthorName { get; init; }

    [JsonPropertyName("hasMainImage")]
    public bool HasMainImage { get; init; }

    [JsonPropertyName("mainImageRef")]
    public string? MainImageRef { get; init; }

    [JsonPropertyName("_type")]
    public string? Type { get; init; }
}
