namespace GwsBusinessSuite.Application.ContentStudio;

public static class ContentStudioImagePreviewFactory
{
    public static ArticleHeroImagePreview CreateGenerated(
        ArticleGenerationRequest request,
        string title,
        string prompt,
        string articleModel,
        string imageModel,
        IReadOnlyCollection<string> availableModels,
        string dataUri)
    {
        var themeLabel = FirstNonEmpty(request.PrimaryKeyword, request.Topic, "Technical article");
        var accentLabel = FirstNonEmpty(FirstKeyword(request.SecondaryKeywords), request.TargetAudience, "Enterprise .NET");
        var altText = $"Hero image for {title}";
        var availableModelsSummary = availableModels.Count == 0
            ? "No model list returned from Ollama."
            : string.Join(", ", availableModels.OrderBy(name => name, StringComparer.OrdinalIgnoreCase));

        var caption = "Generated by local Ollama image model using the exact article brief and SEO context.";

        return new ArticleHeroImagePreview
        {
            Prompt = prompt,
            AltText = altText,
            DataUri = dataUri,
            ThemeLabel = themeLabel,
            AccentLabel = accentLabel,
            Caption = caption,
            Provider = "Ollama",
            ConfiguredModel = imageModel,
            AvailableModelsSummary = availableModelsSummary,
            StatusMessage = $"Hero image generated with model '{imageModel}' while article text used '{articleModel}'.",
            IsGeneratedByOllama = true
        };
    }

    public static ArticleHeroImagePreview CreateUnavailable(
      ArticleGenerationRequest request,
      string title,
            string prompt,
      string articleModel,
      string configuredImageModel,
            IReadOnlyCollection<string> availableModels,
            string? failureReason = null)
    {
        var themeLabel = FirstNonEmpty(request.PrimaryKeyword, request.Topic, "Technical article");
        var accentLabel = FirstNonEmpty(FirstKeyword(request.SecondaryKeywords), request.TargetAudience, "Enterprise .NET");
        var altText = $"Ollama hero image generation status for {title}";
        var availableModelsSummary = availableModels.Count == 0
          ? "No model list returned from Ollama."
          : string.Join(", ", availableModels.OrderBy(name => name, StringComparer.OrdinalIgnoreCase));

        var configuredModel = configuredImageModel.Trim();
        var statusMessage = BuildUnavailableStatus(articleModel, configuredModel, availableModelsSummary, failureReason);
        var caption = "The article prompt is ready for Ollama image generation, but this app is not showing a fake image anymore. It now reports the actual local Ollama image-generation state.";

        return new ArticleHeroImagePreview
        {
            Prompt = prompt,
            AltText = altText,
            ThemeLabel = themeLabel,
            AccentLabel = accentLabel,
            Caption = caption,
            Provider = "Ollama",
            ConfiguredModel = configuredModel,
            AvailableModelsSummary = availableModelsSummary,
            StatusMessage = statusMessage,
            IsGeneratedByOllama = false
        };
    }

    public static string BuildPrompt(ArticleGenerationRequest request, string title)
    {
        return """
        A sleek abstract macro shot of a printed circuit board, glowing copper traces and intricate microchips,
        shallow depth of field with soft bokeh, deep navy and teal tones accented by warm orange light,
        cinematic side lighting, futuristic high-tech software-engineering atmosphere,
        clean and modern, highly detailed, smooth surfaces.
        Negative: text, letters, words, numbers, symbols, people, faces, logos, watermarks, UI chrome.
        """;
    }

    private static string BuildUnavailableStatus(
        string articleModel,
        string configuredImageModel,
        string availableModelsSummary,
        string? failureReason)
    {
        if (!string.IsNullOrWhiteSpace(failureReason))
        {
            return $"Ollama image generation failed. Configured image model: '{configuredImageModel}'. Article generation model: '{articleModel}'. Failure: {failureReason}. Available local models: {availableModelsSummary}";
        }

        if (!string.IsNullOrWhiteSpace(configuredImageModel))
        {
            return $"Ollama image generation is not producing a real image yet. Configured image model: '{configuredImageModel}'. Article generation model: '{articleModel}'. Available local models: {availableModelsSummary}";
        }

        return $"No Ollama image model is configured for Content Studio. The current article model '{articleModel}' generates text, not publish-ready images. Available local models: {availableModelsSummary}";
    }

    private static string FirstKeyword(string value)
    {
        return value
            .Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries)
            .FirstOrDefault()
            ?? string.Empty;
    }

    private static string FirstNonEmpty(params string[] candidates)
    {
        return candidates.FirstOrDefault(candidate => !string.IsNullOrWhiteSpace(candidate))?.Trim() ?? string.Empty;
    }

}
