namespace GwsBusinessSuite.Application.ContentStudio;

public static class ContentStudioImagePreviewFactory
{
    public static ArticleHeroImagePreview CreateGenerated(
        ArticleGenerationRequest request,
        string title,
        string prompt,
        string articleModel,
        string imageModel,
        IReadOnlyCollection<string> availableModels,
        string dataUri)
    {
        var themeLabel = FirstNonEmpty(request.PrimaryKeyword, request.Topic, "Technical article");
        var accentLabel = FirstNonEmpty(FirstKeyword(request.SecondaryKeywords), request.TargetAudience, "Enterprise .NET");
        var altText = $"Hero image for {title}";
        var availableModelsSummary = availableModels.Count == 0
            ? "No model list returned from Ollama."
            : string.Join(", ", availableModels.OrderBy(name => name, StringComparer.OrdinalIgnoreCase));

        var caption = "Generated by local Ollama image model using the exact article brief and SEO context.";

        return new ArticleHeroImagePreview
        {
            Prompt = prompt,
            AltText = altText,
            DataUri = dataUri,
            ThemeLabel = themeLabel,
            AccentLabel = accentLabel,
            Caption = caption,
            Provider = "Ollama",
            ConfiguredModel = imageModel,
            AvailableModelsSummary = availableModelsSummary,
            StatusMessage = $"Hero image generated with model '{imageModel}' while article text used '{articleModel}'.",
            IsGeneratedByOllama = true
        };
    }

    public static ArticleHeroImagePreview CreateUnavailable(
      ArticleGenerationRequest request,
      string title,
            string prompt,
      string articleModel,
      string configuredImageModel,
            IReadOnlyCollection<string> availableModels,
            string? failureReason = null)
    {
        var themeLabel = FirstNonEmpty(request.PrimaryKeyword, request.Topic, "Technical article");
        var accentLabel = FirstNonEmpty(FirstKeyword(request.SecondaryKeywords), request.TargetAudience, "Enterprise .NET");
        var altText = $"Ollama hero image generation status for {title}";
        var availableModelsSummary = availableModels.Count == 0
          ? "No model list returned from Ollama."
          : string.Join(", ", availableModels.OrderBy(name => name, StringComparer.OrdinalIgnoreCase));

        var configuredModel = configuredImageModel.Trim();
        var statusMessage = BuildUnavailableStatus(articleModel, configuredModel, availableModelsSummary, failureReason);
        var caption = "The article prompt is ready for Ollama image generation, but this app is not showing a fake image anymore. It now reports the actual local Ollama image-generation state.";

        return new ArticleHeroImagePreview
        {
            Prompt = prompt,
            AltText = altText,
            ThemeLabel = themeLabel,
            AccentLabel = accentLabel,
            Caption = caption,
            Provider = "Ollama",
            ConfiguredModel = configuredModel,
            AvailableModelsSummary = availableModelsSummary,
            StatusMessage = statusMessage,
            IsGeneratedByOllama = false
        };
    }

    public static string BuildPrompt(ArticleGenerationRequest request, string title)
    {
        var secondaryKeywords = string.IsNullOrWhiteSpace(request.SecondaryKeywords)
            ? "none provided"
            : request.SecondaryKeywords.Trim();
        var stabilizedHeadline = BuildStabilizedHeadline(title);

        return $$"""
        SUBJECT
        Create a production-grade hero image for a professional technical article.
        Topic context: {{request.Topic}}.
        Target audience: {{request.TargetAudience}}.
        Primary keyword context: {{request.PrimaryKeyword}}.
        Secondary keyword context: {{secondaryKeywords}}.

        TYPOGRAPHY RULES
        Use a single short headline only: "{{stabilizedHeadline}}".
        Keep typography to one focal region only.
        Use centered or left-aligned title layout only.
        Avoid text wrapping whenever possible.
        Keep text area minimal and focused.
        Require perfectly legible text, correct spelling, professionally typeset typography, clean sans-serif font, and high contrast behind text.
        Forbid gibberish, malformed letters, distorted typography, fake UI text, multiple unrelated text elements, handwritten fonts, and paragraph text.

        VISUAL STYLE
        Modern enterprise software editorial aesthetic.
        Clean interface-inspired geometry and subtle technical motifs.
        Professional lighting and restrained color palette suitable for business blogs.

        COMPOSITION
        1200x630 aspect ratio.
        Create a clean typography-safe area with uncluttered negative space around the title.
        Maintain strong contrast behind text.
        Avoid busy backgrounds in typography regions.
        Do not include people.

        QUALITY REQUIREMENTS
        Prioritize reliability over artistic experimentation.
        Optimize for realistic typography rendering limitations of diffusion models.
        Verify internally that all text is readable and correctly spelled before finalizing the image.
        If typography is malformed, regenerate the text region before final output.

        NEGATIVE PROMPT
        gibberish text, distorted letters, malformed fonts, unreadable typography, duplicate characters, blurry text, watermark, logo, random symbols

        OUTPUT FORMAT
        Return one final hero image suitable for professional blogs, websites, technical branding, and editorial content.
        """;
    }

    private static string BuildStabilizedHeadline(string title)
    {
        var tokens = title
            .Split(' ', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries)
            .Take(5)
            .Select(token => token.ToUpperInvariant())
            .ToArray();

        return tokens.Length == 0
            ? "TECHNICAL INSIGHTS"
            : string.Join(' ', tokens);
    }

    private static string BuildUnavailableStatus(
        string articleModel,
        string configuredImageModel,
        string availableModelsSummary,
        string? failureReason)
    {
        if (!string.IsNullOrWhiteSpace(failureReason))
        {
            return $"Ollama image generation failed. Configured image model: '{configuredImageModel}'. Article generation model: '{articleModel}'. Failure: {failureReason}. Available local models: {availableModelsSummary}";
        }

        if (!string.IsNullOrWhiteSpace(configuredImageModel))
        {
            return $"Ollama image generation is not producing a real image yet. Configured image model: '{configuredImageModel}'. Article generation model: '{articleModel}'. Available local models: {availableModelsSummary}";
        }

        return $"No Ollama image model is configured for Content Studio. The current article model '{articleModel}' generates text, not publish-ready images. Available local models: {availableModelsSummary}";
    }

    private static string FirstKeyword(string value)
    {
        return value
            .Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries)
            .FirstOrDefault()
            ?? string.Empty;
    }

    private static string FirstNonEmpty(params string[] candidates)
    {
        return candidates.FirstOrDefault(candidate => !string.IsNullOrWhiteSpace(candidate))?.Trim() ?? string.Empty;
    }

}
